# Generated by Django 3.2.10 on 2021-12-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(max_length=500, null=True)),
                ('title', models.IntegerField(max_length=500, null=True)),
                ('run_date', models.DateField()),
            ],
            options={
                'db_table': 'test_allowed',
            },
        ),
    ]
